insert into wine_rating (wine_id, user, date, rating) values (63,'nickwellman','11/24/21','check plus');
insert into wine_rating (wine_id, user, date, rating) values (64,'nickwellman','11/24/21','check plus plus');
insert into wine_rating (wine_id, user, date, rating) values (71,'nickwellman','11/24/21','check minus');
insert into wine_rating (wine_id, user, date, rating) values (66,'nickwellman','11/24/21','check');
insert into wine_rating (wine_id, user, date, rating) values (68,'nickwellman','11/24/21','check');
insert into wine_rating (wine_id, user, date, rating) values (67,'nickwellman','11/24/21','check');
insert into wine_rating (wine_id, user, date, rating) values (55,'nickwellman','9/12/21','');
insert into wine_rating (wine_id, user, date, rating) values (56,'nickwellman','9/12/21','');
insert into wine_rating (wine_id, user, date, rating) values (57,'nickwellman','9/12/21','check');
insert into wine_rating (wine_id, user, date, rating) values (58,'nickwellman','9/12/21','');
insert into wine_rating (wine_id, user, date, rating) values (59,'nickwellman','9/12/21','');
insert into wine_rating (wine_id, user, date, rating) values (60,'nickwellman','9/12/21','');
insert into wine_rating (wine_id, user, date, rating) values (61,'nickwellman','9/12/21','check check');
insert into wine_rating (wine_id, user, date, rating) values (62,'nickwellman','9/12/21','check');
insert into wine_rating (wine_id, user, date, rating) values (49,'nickwellman','12/5/21','');
insert into wine_rating (wine_id, user, date, rating) values (50,'nickwellman','12/5/21','');
insert into wine_rating (wine_id, user, date, rating) values (71,'nickwellman','12/5/21','');
insert into wine_rating (wine_id, user, date, rating) values (52,'nickwellman','12/5/21','');
insert into wine_rating (wine_id, user, date, rating) values (53,'nickwellman','12/5/21','');
insert into wine_rating (wine_id, user, date, rating) values (54,'nickwellman','12/5/21','');
insert into wine_rating (wine_id, user, date, rating) values (42,'nickwellman','12/17/21','check check');
insert into wine_rating (wine_id, user, date, rating) values (43,'nickwellman','12/17/21','');
insert into wine_rating (wine_id, user, date, rating) values (44,'nickwellman','12/17/21','');
insert into wine_rating (wine_id, user, date, rating) values (45,'nickwellman','12/17/21','check');
insert into wine_rating (wine_id, user, date, rating) values (46,'nickwellman','12/17/21','check');
insert into wine_rating (wine_id, user, date, rating) values (47,'nickwellman','12/17/21','');
insert into wine_rating (wine_id, user, date, rating) values (48,'nickwellman','12/17/21','check plus');
insert into wine_rating (wine_id, user, date, rating) values (69,'nickwellman','8/14/211','minus');
insert into wine_rating (wine_id, user, date, rating) values (70,'nickwellman','8/14/211','check check');
insert into wine_rating (wine_id, user, date, rating) values (71,'nickwellman','8/14/211','check');
insert into wine_rating (wine_id, user, date, rating) values (72,'nickwellman','8/14/211','minus');
insert into wine_rating (wine_id, user, date, rating) values (73,'nickwellman','8/14/211','check check');
insert into wine_rating (wine_id, user, date, rating) values (75,'nickwellman','8/14/211','check');
insert into wine_rating (wine_id, user, date, rating) values (37,'nickwellman','9/5/21','check checck');
insert into wine_rating (wine_id, user, date, rating) values (32,'nickwellman','9/5/21','');
insert into wine_rating (wine_id, user, date, rating) values (33,'nickwellman','9/5/21','check');
insert into wine_rating (wine_id, user, date, rating) values (34,'nickwellman','9/5/21','check check');
insert into wine_rating (wine_id, user, date, rating) values (35,'nickwellman','9/5/21','');
insert into wine_rating (wine_id, user, date, rating) values (26,'nickwellman','11/6/21','check check');
insert into wine_rating (wine_id, user, date, rating) values (39,'nickwellman','11/6/21','');
insert into wine_rating (wine_id, user, date, rating) values (28,'nickwellman','11/6/21','');
insert into wine_rating (wine_id, user, date, rating) values (29,'nickwellman','11/6/21','');
insert into wine_rating (wine_id, user, date, rating) values (30,'nickwellman','11/6/21','');
insert into wine_rating (wine_id, user, date, rating) values (25,'nickwellman','9/4/21','check minus');
insert into wine_rating (wine_id, user, date, rating) values (22,'nickwellman','9/4/21','check');
insert into wine_rating (wine_id, user, date, rating) values (23,'nickwellman','9/4/21','check plus');
insert into wine_rating (wine_id, user, date, rating) values (24,'nickwellman','9/4/21','check check');
insert into wine_rating (wine_id, user, date, rating) values (5,'nickwellman','9/4/21','check');
insert into wine_rating (wine_id, user, date, rating) values (6,'nickwellman','9/4/21','');
insert into wine_rating (wine_id, user, date, rating) values (7,'nickwellman','9/4/21','check check');
insert into wine_rating (wine_id, user, date, rating) values (8,'nickwellman','9/4/21','');
insert into wine_rating (wine_id, user, date, rating) values (21,'nickwellman','9/4/21','');
insert into wine_rating (wine_id, user, date, rating) values (1,'nickwellman','11/6/21','');
insert into wine_rating (wine_id, user, date, rating) values (2,'nickwellman','11/6/21','check');
insert into wine_rating (wine_id, user, date, rating) values (3,'nickwellman','11/6/21','');
insert into wine_rating (wine_id, user, date, rating) values (4,'nickwellman','11/6/21','check');
