insert into wine_notes (wine_id, user, date, note, ordinal) values (69, 'nickwellman', '8/14/21', 'Nice up front not a fan of after taste', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (70, 'nickwellman', '8/14/21', 'Dry but tasty', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (71, 'nickwellman', '8/14/21', 'ok', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (71, 'nickwellman', '8/14/21', 'a bit tangy', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (72, 'nickwellman', '8/14/21', 'black cherry', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (72, 'nickwellman', '8/14/21', 'not a big fan', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (73, 'nickwellman', '8/14/21', 'blueberry', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (73, 'nickwellman', '8/14/21', 'plum', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (73, 'nickwellman', '8/14/21', 'sweet, but i like it', 2);
insert into wine_notes (wine_id, user, date, note, ordinal) values (74, 'nickwellman', '8/14/21', 'apple', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (74, 'nickwellman', '8/14/21', 'butterscotch', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (74, 'nickwellman', '8/14/21', 'smooth', 2);
insert into wine_notes (wine_id, user, date, note, ordinal) values (74, 'nickwellman', '8/14/21', 'viscus', 3);
insert into wine_notes (wine_id, user, date, note, ordinal) values (75, 'nickwellman', '8/14/21', 'smooth texture', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (75, 'nickwellman', '8/14/21', 'not as grapy as i hoped', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (42, 'nickwellman', '12/17/21', 'semi-dry', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (42, 'nickwellman', '12/17/21', 'crisp', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (43, 'nickwellman', '12/17/21', 'sweet', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (43, 'nickwellman', '12/17/21', 'peach', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (43, 'nickwellman', '12/17/21', 'pineapple', 2);
insert into wine_notes (wine_id, user, date, note, ordinal) values (44, 'nickwellman', '12/17/21', 'pear', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (44, 'nickwellman', '12/17/21', 'feels a bit flat after nancie', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (44, 'nickwellman', '12/17/21', 'needed to swirl mouth', 2);
insert into wine_notes (wine_id, user, date, note, ordinal) values (45, 'nickwellman', '12/17/21', 'semi-sweet', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (45, 'nickwellman', '12/17/21', 'straw', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (45, 'nickwellman', '12/17/21', 'cherry', 2);
insert into wine_notes (wine_id, user, date, note, ordinal) values (46, 'nickwellman', '12/17/21', 'full-bodied', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (46, 'nickwellman', '12/17/21', 'leather', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (48, 'nickwellman', '12/17/21', 'port', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (48, 'nickwellman', '12/17/21', 'sherry', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (48, 'nickwellman', '12/17/21', 'taste like a port', 2);
insert into wine_notes (wine_id, user, date, note, ordinal) values (49, 'nickwellman', '12/5/21', 'dry', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (49, 'nickwellman', '12/5/21', 'acidic', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (55, 'nickwellman', '9/12/21', 'herb aromas', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (55, 'nickwellman', '9/12/21', 'blossom', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (55, 'nickwellman', '9/12/21', 'green apple', 2);
insert into wine_notes (wine_id, user, date, note, ordinal) values (55, 'nickwellman', '9/12/21', 'tart', 3);
insert into wine_notes (wine_id, user, date, note, ordinal) values (56, 'nickwellman', '9/12/21', 'green apple', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (56, 'nickwellman', '9/12/21', 'white pepper nose', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (57, 'nickwellman', '9/12/21', 'medium acidity', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (57, 'nickwellman', '9/12/21', 'pear', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (57, 'nickwellman', '9/12/21', 'sweet but not cloying', 2);
insert into wine_notes (wine_id, user, date, note, ordinal) values (58, 'nickwellman', '9/12/21', 'sweet', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (58, 'nickwellman', '9/12/21', 'sweet tea', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (59, 'nickwellman', '9/12/21', 'high tannins', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (59, 'nickwellman', '9/12/21', 'black cherry', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (59, 'nickwellman', '9/12/21', 'dry', 2);
insert into wine_notes (wine_id, user, date, note, ordinal) values (60, 'nickwellman', '9/12/21', 'currant', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (60, 'nickwellman', '9/12/21', 'bing cherry', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (60, 'nickwellman', '9/12/21', 'nope', 2);
insert into wine_notes (wine_id, user, date, note, ordinal) values (61, 'nickwellman', '9/12/21', 'red grape aromas', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (62, 'nickwellman', '9/12/21', 'blueberry', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (62, 'nickwellman', '9/12/21', 'mixed berry pie', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (62, 'nickwellman', '9/12/21', 'cherries', 2);
insert into wine_notes (wine_id, user, date, note, ordinal) values (62, 'nickwellman', '9/12/21', 'cranberry', 3);
insert into wine_notes (wine_id, user, date, note, ordinal) values (62, 'nickwellman', '9/12/21', 'could be a port', 4);
