insert into wine_notes (wine_id, user, date, note, ordinal) values (69, 'nickwellman', '8/14/21', 'Nice up front not a fan of after taste', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (70, 'nickwellman', '8/14/21', 'Dry but tasty', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (71, 'nickwellman', '8/14/21', 'ok', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (71, 'nickwellman', '8/14/21', 'a bit tangy', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (72, 'nickwellman', '8/14/21', 'black cherry', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (72, 'nickwellman', '8/14/21', 'not a big fan', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (73, 'nickwellman', '8/14/21', 'blueberry', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (73, 'nickwellman', '8/14/21', 'plum', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (73, 'nickwellman', '8/14/21', 'sweet, but i like it', 2);
insert into wine_notes (wine_id, user, date, note, ordinal) values (74, 'nickwellman', '8/14/21', 'apple', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (74, 'nickwellman', '8/14/21', 'butterscotch', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (74, 'nickwellman', '8/14/21', 'smooth', 2);
insert into wine_notes (wine_id, user, date, note, ordinal) values (74, 'nickwellman', '8/14/21', 'viscus', 3);
insert into wine_notes (wine_id, user, date, note, ordinal) values (75, 'nickwellman', '8/14/21', 'smooth texture', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (75, 'nickwellman', '8/14/21', 'not as grapy as i hoped', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (42, 'nickwellman', '12/17/21', 'semi-dry', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (42, 'nickwellman', '12/17/21', 'crisp', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (43, 'nickwellman', '12/17/21', 'sweet', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (43, 'nickwellman', '12/17/21', 'peach', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (43, 'nickwellman', '12/17/21', 'pineapple', 2);
insert into wine_notes (wine_id, user, date, note, ordinal) values (44, 'nickwellman', '12/17/21', 'pear', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (44, 'nickwellman', '12/17/21', 'feels a bit flat after nancie', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (44, 'nickwellman', '12/17/21', 'needed to swirl mouth', 2);
insert into wine_notes (wine_id, user, date, note, ordinal) values (45, 'nickwellman', '12/17/21', 'semi-sweet', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (45, 'nickwellman', '12/17/21', 'straw', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (45, 'nickwellman', '12/17/21', 'cherry', 2);
insert into wine_notes (wine_id, user, date, note, ordinal) values (46, 'nickwellman', '12/17/21', 'full-bodied', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (46, 'nickwellman', '12/17/21', 'leather', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (48, 'nickwellman', '12/17/21', 'port', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (48, 'nickwellman', '12/17/21', 'sherry', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (48, 'nickwellman', '12/17/21', 'taste like a port', 2);
insert into wine_notes (wine_id, user, date, note, ordinal) values (49, 'nickwellman', '12/5/21', 'dry', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (49, 'nickwellman', '12/5/21', 'acidic', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (55, 'nickwellman', '9/12/21', 'herb aromas', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (55, 'nickwellman', '9/12/21', 'blossom', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (55, 'nickwellman', '9/12/21', 'green apple', 2);
insert into wine_notes (wine_id, user, date, note, ordinal) values (55, 'nickwellman', '9/12/21', 'tart', 3);
insert into wine_notes (wine_id, user, date, note, ordinal) values (56, 'nickwellman', '9/12/21', 'green apple', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (56, 'nickwellman', '9/12/21', 'white pepper nose', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (57, 'nickwellman', '9/12/21', 'medium acidity', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (57, 'nickwellman', '9/12/21', 'pear', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (57, 'nickwellman', '9/12/21', 'sweet but not cloying', 2);
insert into wine_notes (wine_id, user, date, note, ordinal) values (58, 'nickwellman', '9/12/21', 'sweet', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (58, 'nickwellman', '9/12/21', 'sweet tea', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (59, 'nickwellman', '9/12/21', 'high tannins', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (59, 'nickwellman', '9/12/21', 'black cherry', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (59, 'nickwellman', '9/12/21', 'dry', 2);
insert into wine_notes (wine_id, user, date, note, ordinal) values (60, 'nickwellman', '9/12/21', 'currant', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (60, 'nickwellman', '9/12/21', 'bing cherry', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (60, 'nickwellman', '9/12/21', 'nope', 2);
insert into wine_notes (wine_id, user, date, note, ordinal) values (61, 'nickwellman', '9/12/21', 'red grape aromas', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (62, 'nickwellman', '9/12/21', 'blueberry', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (62, 'nickwellman', '9/12/21', 'mixed berry pie', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (62, 'nickwellman', '9/12/21', 'cherries', 2);
insert into wine_notes (wine_id, user, date, note, ordinal) values (62, 'nickwellman', '9/12/21', 'cranberry', 3);
insert into wine_notes (wine_id, user, date, note, ordinal) values (62, 'nickwellman', '9/12/21', 'could be a port', 4);
insert into wine_notes (wine_id, user, date, note, ordinal) values (63, 'nickwellman', '11/24/21', 'lemon', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (63, 'nickwellman', '11/24/21', 'apple', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (63, 'nickwellman', '11/24/21', 'clean', 2);
insert into wine_notes (wine_id, user, date, note, ordinal) values (64, 'nickwellman', '11/24/21', 'medium-bodied', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (64, 'nickwellman', '11/24/21', 'aromas', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (64, 'nickwellman', '11/24/21', 'dark cherry', 2);
insert into wine_notes (wine_id, user, date, note, ordinal) values (64, 'nickwellman', '11/24/21', 'black currants', 3);
insert into wine_notes (wine_id, user, date, note, ordinal) values (64, 'nickwellman', '11/24/21', 'dark cherry', 4);
insert into wine_notes (wine_id, user, date, note, ordinal) values (64, 'nickwellman', '11/24/21', 'why sweeter than it should be', 5);
insert into wine_notes (wine_id, user, date, note, ordinal) values (71, 'nickwellman', '11/24/21', 'honeycrisp apple flavors', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (66, 'nickwellman', '11/24/21', 'grape grape grape', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (68, 'nickwellman', '11/24/21', 'red currant and dried cranberry', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (68, 'nickwellman', '11/24/21', 'its fine', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (67, 'nickwellman', '11/24/21', 'boozy', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (67, 'nickwellman', '11/24/21', 'creamy', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (99, 'nickwellman', '9/5/21', 'bright', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (99, 'nickwellman', '9/5/21', 'lots of acid', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (100, 'nickwellman', '9/5/21', 'butter peanuts', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (101, 'nickwellman', '9/5/21', 'buttery oak', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (102, 'nickwellman', '9/5/21', 'oak', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (102, 'nickwellman', '9/5/21', 'spice', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (103, 'nickwellman', '9/5/21', 'thick', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (103, 'nickwellman', '9/5/21', 'good with chocolate', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (104, 'nickwellman', '9/4/21', 'dry tannin', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (105, 'nickwellman', '9/4/21', 'tart', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (105, 'nickwellman', '9/4/21', 'meh', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (106, 'nickwellman', '9/4/21', 'dryyyy', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (107, 'nickwellman', '9/4/21', 'berry', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (107, 'nickwellman', '9/4/21', 'pepper', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (107, 'nickwellman', '9/4/21', 'meh', 2);
insert into wine_notes (wine_id, user, date, note, ordinal) values (90, 'nickwellman', '11/6/21', 'ginger', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (90, 'nickwellman', '11/6/21', 'peach', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (82, 'nickwellman', '9/4/21', 'stainless steel', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (82, 'nickwellman', '9/4/21', 'acid', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (83, 'nickwellman', '9/4/21', 'tannins', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (84, 'nickwellman', '9/4/21', 'sweet for a brut', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (84, 'nickwellman', '9/4/21', 'growing on me', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (85, 'nickwellman', '9/4/21', 'concentrated', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (86, 'nickwellman', '9/4/21', 'raspberry', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (76, 'nickwellman', '11/6/21', 'too many apple', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (77, 'nickwellman', '11/6/21', 'a little tart', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (80, 'nickwellman', '11/6/21', 'tart', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (80, 'nickwellman', '11/6/21', 'metalic after taste', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (80, 'nickwellman', '11/6/21', 'maybe from oyster cracker', 2);
insert into wine_notes (wine_id, user, date, note, ordinal) values (81, 'nickwellman', '11/6/21', 'cough wyrup', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (1, 'nickwellman', '11/6/21', 'berry fruit', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (2, 'nickwellman', '11/6/21', 'riesling', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (3, 'nickwellman', '11/6/21', 'dark fruit flavors', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (4, 'nickwellman', '11/6/21', 'tasty', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (4, 'nickwellman', '11/6/21', 'a bit tart', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (5, 'nickwellman', '9/4/21', 'sweet', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (5, 'nickwellman', '9/4/21', 'acidic', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (6, 'nickwellman', '9/4/21', 'fruit', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (6, 'nickwellman', '9/4/21', 'soft tannins', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (6, 'nickwellman', '9/4/21', 'not as sweet as i hoped', 2);
insert into wine_notes (wine_id, user, date, note, ordinal) values (7, 'nickwellman', '9/4/21', 'berry notes palate', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (39, 'nickwellman', '11/6/21', 'watering finish', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (39, 'nickwellman', '11/6/21', 'seems sweet', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (39, 'nickwellman', '11/6/21', 'not what i want', 2);
insert into wine_notes (wine_id, user, date, note, ordinal) values (28, 'nickwellman', '11/6/21', 'lime', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (28, 'nickwellman', '11/6/21', 'semi-sweet', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (30, 'nickwellman', '11/6/21', 'plum', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (30, 'nickwellman', '11/6/21', 'rich', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (30, 'nickwellman', '11/6/21', 'dry', 2);
insert into wine_notes (wine_id, user, date, note, ordinal) values (37, 'nickwellman', '9/5/21', 'yum', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (32, 'nickwellman', '9/5/21', 'french oak', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (33, 'nickwellman', '9/5/21', 'bright citrus', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (34, 'nickwellman', '9/5/21', 'dry', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (34, 'nickwellman', '9/5/21', 'fruity', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (34, 'nickwellman', '9/5/21', 'not very tanniny, which is nice', 2);
insert into wine_notes (wine_id, user, date, note, ordinal) values (36, 'nickwellman', '9/5/21', 'berry', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (36, 'nickwellman', '9/5/21', 'pepper', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (35, 'nickwellman', '9/5/21', 'full bodied red', 0);
insert into wine_notes (wine_id, user, date, note, ordinal) values (35, 'nickwellman', '9/5/21', 'tannins', 1);
insert into wine_notes (wine_id, user, date, note, ordinal) values (35, 'nickwellman', '9/5/21', 'hits you', 2);
