insert into wines (winery_id, name, style) values (11,'2017 Pinot Grigio','Dry White');
insert into wines (winery_id, name, style) values (11,'Festivus','Dry Red');
insert into wines (winery_id, name, style) values (11,'Winter Wite','Sweet White');
insert into wines (winery_id, name, style) values (11,'Great Lakes Red','Sweet Red');
insert into wines (winery_id, name, style) values (11,'Cherry','Fruit Wine');
insert into wines (winery_id, name, style) values (11,'Raspberry Dessert Wine','Dessert Wine');
insert into wines (winery_id, name, style) values (11,'2018 Chardonnay','Dry White');
insert into wines (winery_id, name, style) values (11,'Sleeping Bear Red','Dry Red');
insert into wines (winery_id, name, style) values (11,'2020 Brut','Sparkling');
insert into wines (winery_id, name, style) values (11,'Winter White Bubbly','Sparkling');
insert into wines (winery_id, name, style) values (11,'2018 Vintage Port','Dessert Wine');

insert into wine_rating (wine_id, user, date, rating) values (82,'nickwellman','9/4/21','');
insert into wine_rating (wine_id, user, date, rating) values (83,'nickwellman','9/4/21','');
insert into wine_rating (wine_id, user, date, rating) values (84,'nickwellman','9/4/21','check');
insert into wine_rating (wine_id, user, date, rating) values (85,'nickwellman','9/4/21','');
insert into wine_rating (wine_id, user, date, rating) values (86,'nickwellman','9/4/21','');
insert into wine_rating (wine_id, user, date, rating) values (76,'nickwellman','11/6/21','');
insert into wine_rating (wine_id, user, date, rating) values (77,'nickwellman','11/6/21','');
insert into wine_rating (wine_id, user, date, rating) values (78,'nickwellman','11/6/21','check check');
insert into wine_rating (wine_id, user, date, rating) values (79,'nickwellman','11/6/21','check check');
insert into wine_rating (wine_id, user, date, rating) values (80,'nickwellman','11/6/21','check');
insert into wine_rating (wine_id, user, date, rating) values (81,'nickwellman','11/6/21','');

insert into wines (winery_id, name, style) values (16,'2017 Riesling','Hard Cider');
insert into wines (winery_id, name, style) values (16,'Old World','Hard Cider');
insert into wines (winery_id, name, style) values (16,'Cherry','Hard Cider');
insert into wines (winery_id, name, style) values (16,'Sangria','Hard Cider');
insert into wines (winery_id, name, style) values (16,'2020 Honeycrisp Ice Cider','Hard Cider');
insert into wines (winery_id, name, style) values (15,'Horseradish Vodka','Spirit');
insert into wines (winery_id, name, style) values (15,'Jack Pine Gin','Spirit');
insert into wines (winery_id, name, style) values (15,'Bernies Brandy','Spirit');
insert into wines (winery_id, name, style) values (15,'Deer Camp Straight Bourbon Whiskey','Spirit');
insert into wines (winery_id, name, style) values (15,'Deer Camp Vodka','Spirit');
insert into wines (winery_id, name, style) values (15,'Manitou Passage Rum','Spirit');
insert into wines (winery_id, name, style) values (15,'Michigan Dogman Moonshine','Spirit');

insert into wine_rating (wine_id, user, date, rating) values (96,'nickwellman','9/4/21','');
insert into wine_rating (wine_id, user, date, rating) values (97,'nickwellman','9/4/21','');
insert into wine_rating (wine_id, user, date, rating) values (94,'nickwellman','9/4/21','');
insert into wine_rating (wine_id, user, date, rating) values (95,'nickwellman','9/4/21','');
insert into wine_rating (wine_id, user, date, rating) values (98,'nickwellman','9/4/21','check');
insert into wine_rating (wine_id, user, date, rating) values (92,'nickwellman','11/6/21','');
insert into wine_rating (wine_id, user, date, rating) values (93,'nickwellman','11/6/21','');
insert into wine_rating (wine_id, user, date, rating) values (94,'nickwellman','11/6/21','');
insert into wine_rating (wine_id, user, date, rating) values (95,'nickwellman','11/6/21','');
insert into wine_rating (wine_id, user, date, rating) values (87,'nickwellman','11/6/21','');
insert into wine_rating (wine_id, user, date, rating) values (88,'nickwellman','11/6/21','');
insert into wine_rating (wine_id, user, date, rating) values (89,'nickwellman','11/6/21','');
insert into wine_rating (wine_id, user, date, rating) values (90,'nickwellman','11/6/21','check');
insert into wine_rating (wine_id, user, date, rating) values (91,'nickwellman','11/6/21','');

insert into wines (winery_id, name, style) values (9,'2019 Dry Riesling','White');
insert into wines (winery_id, name, style) values (9,'2019 Unwooded Chardonnay','White');
insert into wines (winery_id, name, style) values (9,'2017 Pinot Gris','White');
insert into wines (winery_id, name, style) values (9,'2019 Skin Ferment Pinot Gris','Rose');
insert into wines (winery_id, name, style) values (9,'Cherry Dessert','Dessert Wine');
insert into wines (winery_id, name, style) values (10,'2019 Soiree','Sparkling');
insert into wines (winery_id, name, style) values (10,'2019 Rose de Pinot Noir','Rose');
insert into wines (winery_id, name, style) values (10,'2018 Lee La Tage','Red Wine');
insert into wines (winery_id, name, style) values (10,'2019 Ridge Red','Red Wine');

insert into wine_rating (wine_id, user, date, rating) values (104,'nickwellman','9/4/21','');
insert into wine_rating (wine_id, user, date, rating) values (105,'nickwellman','9/4/21','');
insert into wine_rating (wine_id, user, date, rating) values (106,'nickwellman','9/4/21','');
insert into wine_rating (wine_id, user, date, rating) values (107,'nickwellman','9/4/21','');
insert into wine_rating (wine_id, user, date, rating) values (99,'nickwellman','9/5/21','');
insert into wine_rating (wine_id, user, date, rating) values (100,'nickwellman','9/5/21','');
insert into wine_rating (wine_id, user, date, rating) values (101,'nickwellman','9/5/21','');
insert into wine_rating (wine_id, user, date, rating) values (102,'nickwellman','9/5/21','');
insert into wine_rating (wine_id, user, date, rating) values (103,'nickwellman','9/5/21','check');
