insert into wines (winery_id, name, rating, style, date) values (12,'Arcturos Pinot Noir Rose','','Pinot Noir Rose','11/6/21');
insert into wines (winery_id, name, rating, style, date) values (12,'Tribute Off-Dry Riesling','check','Riesling','11/6/21');
insert into wines (winery_id, name, rating, style, date) values (12,'Vintners Select','','Red','11/6/21');
insert into wines (winery_id, name, rating, style, date) values (12,'Black Star Farms Hard Apple Cherry Cider','check','Cider','11/6/21');
insert into wines (winery_id, name, rating, style, date) values (12,'Arcturos Pinot Noir Blanc','check','White','9/4/21');
insert into wines (winery_id, name, rating, style, date) values (12,'Artisan Red','','Red','9/4/21');
insert into wines (winery_id, name, rating, style, date) values (12,'Red House Rose','check check','Rose','9/4/21');
insert into wines (winery_id, name, rating, style, date) values (12,'Spirit of the Vineyard Red Grappa','','Spirit','9/4/21');
insert into wines (winery_id, name, rating, style, date) values (12,'Spirit of Apple Brandy','','Spirit','9/4/21');
insert into wines (winery_id, name, rating, style, date) values (12,'Wine Club Selection Sparkling Riesling','','Sparkling','9/4/21');
insert into wines (winery_id, name, rating, style, date) values (12,'Arcturos Gewurztraminer','','Gewurztraminer','9/4/21');
insert into wines (winery_id, name, rating, style, date) values (12,'Black Star Farms Hard Apple Cherry Cider','circle','Cider','9/4/21');
insert into wines (winery_id, name, rating, style, date) values (12,'Red House Rose','circle','Rose','9/4/21');
insert into wines (winery_id, name, rating, style, date) values (12,'Arcturos Dry Riesling','','Riesling','');
insert into wines (winery_id, name, rating, style, date) values (12,'Arcturos Sur Lie Chardonnay','','Chardonnay','');
insert into wines (winery_id, name, rating, style, date) values (12,'Red House Rose','','Rose','');
insert into wines (winery_id, name, rating, style, date) values (12,'Black Star Farms Pear Wine','','Fruit','');
insert into wines (winery_id, name, rating, style, date) values (12,'Artisan Red','','Sweet Red','');
insert into wines (winery_id, name, rating, style, date) values (12,'Sirius Red Dessert Wine','','Dessert','');
insert into wines (winery_id, name, rating, style, date) values (12,'Spirit of the Vineyard Red Grappa','','Spirit','');
insert into wines (winery_id, name, rating, style, date) values (12,'Spirit of Apple Brandy','','Spirit','');
insert into wines (winery_id, name, rating, style, date) values (14,'Tropic','check','Sparkling','9/4/21');
insert into wines (winery_id, name, rating, style, date) values (14,'Green','check plus','Sparkling','9/4/21');
insert into wines (winery_id, name, rating, style, date) values (14,'Grace','check check','Sparkling','9/4/21');
insert into wines (winery_id, name, rating, style, date) values (14,'Sunlight','check minus','Sparkling','9/4/21');
insert into wines (winery_id, name, rating, style, date) values (7,'Brute Rose','check check','Sparkling','11/6/21');
insert into wines (winery_id, name, rating, style, date) values (7,'Dry Riesling','','Riesling','11/6/21');
insert into wines (winery_id, name, rating, style, date) values (7,'Gruner Veltliner 2020','','White','11/6/21');
insert into wines (winery_id, name, rating, style, date) values (7,'Blaufrankisch 2017','','Red','11/6/21');
insert into wines (winery_id, name, rating, style, date) values (7,'Cabernet Franc 2017','','Red','11/6/21');
insert into wines (winery_id, name, rating, style, date) values (7,'Blanc De Noirs','check check','Sparkling','11/6/21');
insert into wines (winery_id, name, rating, style, date) values (7,'Barrel Fermented Chardonnay 2017','','Chardonnay','9/5/21');
insert into wines (winery_id, name, rating, style, date) values (7,'Pinot Grigio 2018','check','Pinto Grigio','9/5/21');
insert into wines (winery_id, name, rating, style, date) values (7,'Radiance','check check','Red','9/5/21');
insert into wines (winery_id, name, rating, style, date) values (7,'Rosso','','Red','9/5/21');
insert into wines (winery_id, name, rating, style, date) values (7,'Blaufrankisch 2016','','Red','9/5/21');
insert into wines (winery_id, name, rating, style, date) values (7,'Blanc De Noirs','','Sparkling','9/5/21');
insert into wines (winery_id, name, rating, style, date) values (7,'Serata Demi-Sec','','Sparkling','9/5/21');
insert into wines (winery_id, name, rating, style, date) values (7,'Dry Riesling 2020','','Riesling','9/5/21');
insert into wines (winery_id, name, rating, style, date) values (7,'Medium Sweet Gewurztraminer 2020','','Gewurztraminer','9/5/21');
insert into wines (winery_id, name, rating, style, date) values (7,'Blaufrankisch','','Red','9/5/21');
insert into wines (winery_id, name, rating, style, date) values (1,'Brut Champagne','check check','Sparkling','12/17/21');
insert into wines (winery_id, name, rating, style, date) values (1,'Sweet Nancie','','Sparkling','12/17/21');
insert into wines (winery_id, name, rating, style, date) values (1,'BR Gruner Veltliner','','White','12/17/21');
insert into wines (winery_id, name, rating, style, date) values (1,'Outlook','check','Rose','12/17/21');
insert into wines (winery_id, name, rating, style, date) values (1,'Michigan Awesome Red','check','Red','12/17/21');
insert into wines (winery_id, name, rating, style, date) values (1,'Bourbon','','Spirit','12/17/21');
insert into wines (winery_id, name, rating, style, date) values (1,'Founders Pride','check plus','Dessert','12/17/21');
insert into wines (winery_id, name, rating, style, date) values (1,'BR Blanc de Blanc','','Sparkling','12/5/21');
insert into wines (winery_id, name, rating, style, date) values (1,'Ciao Bolle','','Sparkling','12/5/21');
insert into wines (winery_id, name, rating, style, date) values (1,'Reserve Pinot Grigio','','Pinot Grigio','12/5/21');
insert into wines (winery_id, name, rating, style, date) values (1,'Cento','','Sweet Red','12/5/21');
insert into wines (winery_id, name, rating, style, date) values (1,'Cherry Hard Cider','','Cider','12/5/21');
insert into wines (winery_id, name, rating, style, date) values (1,'Original Hard Cider','','Cider','12/5/21');
insert into wines (winery_id, name, rating, style, date) values (1,'BR Albarino','','White','9/12/21');
insert into wines (winery_id, name, rating, style, date) values (1,'Mayhem','','White','9/12/21');
insert into wines (winery_id, name, rating, style, date) values (1,'Unparalleled Sweet','check','White','9/12/21');
insert into wines (winery_id, name, rating, style, date) values (1,'BR Late Harvest Vignoles','','White','9/12/21');
insert into wines (winery_id, name, rating, style, date) values (1,'BR Cabernet Sauvignon','','Red','9/12/21');
insert into wines (winery_id, name, rating, style, date) values (1,'BR Chancellor','','Red','9/12/21');
insert into wines (winery_id, name, rating, style, date) values (1,'Red Heron','check check','Sweet Red','9/12/21');
insert into wines (winery_id, name, rating, style, date) values (1,'BR Meconi','check','Sweet Red','9/12/21');
insert into wines (winery_id, name, rating, style, date) values (1,'2020 Winemakers Series Unoaked Chardonnay','check plus','Chardonnay','11/24/21');
insert into wines (winery_id, name, rating, style, date) values (1,'2018 BR Tempranillo','check plus plus','Ree','11/24/21');
insert into wines (winery_id, name, rating, style, date) values (1,'Reserve Pinot Grigio','check minus','Pinot Grigio','11/24/21');
insert into wines (winery_id, name, rating, style, date) values (1,'Sweet Revenge','check','Sweet Red','11/24/21');
insert into wines (winery_id, name, rating, style, date) values (1,'Egg Nog','check','Dessert','11/24/21');
insert into wines (winery_id, name, rating, style, date) values (1,'Cranberry','check','Fruit','11/24/21');
insert into wines (winery_id, name, rating, style, date) values (1,'2020 WMS White Cabernet Franc','minus','White','8/14/21');
insert into wines (winery_id, name, rating, style, date) values (1,'2018 Signature Series Dry Red Blend','check check','Red','8/14/21');
insert into wines (winery_id, name, rating, style, date) values (1,'Reserve Pinot Grigio','check','Pinot Grigio','8/14/21');
insert into wines (winery_id, name, rating, style, date) values (1,'Coastline Red Blend','minus','Red','8/14/21');
insert into wines (winery_id, name, rating, style, date) values (1,'BR Petite Pearl','check check','Red','8/14/21');
insert into wines (winery_id, name, rating, style, date) values (1,'Apple Brandy','check check','Spirit','8/14/21');
insert into wines (winery_id, name, rating, style, date) values (1,'Vodka Made from Grapes','check','Spirit','8/14/21');
