insert into wines (winery_id, name, style) values (12,'Arcturos Pinot Noir Rose','Pinot Noir Rose');
insert into wines (winery_id, name, style) values (12,'Tribute Off-Dry Riesling','Riesling');
insert into wines (winery_id, name, style) values (12,'Vintners Select','Red');
insert into wines (winery_id, name, style) values (12,'Black Star Farms Hard Apple Cherry Cider','Cider');
insert into wines (winery_id, name, style) values (12,'Arcturos Pinot Noir Blanc','White');
insert into wines (winery_id, name, style) values (12,'Artisan Red','Red');
insert into wines (winery_id, name, style) values (12,'Red House Rose','Rose');
insert into wines (winery_id, name, style) values (12,'Spirit of the Vineyard Red Grappa','Spirit');
insert into wines (winery_id, name, style) values (12,'Spirit of Apple Brandy','Spirit');
insert into wines (winery_id, name, style) values (12,'Wine Club Selection Sparkling Riesling','Sparkling');
insert into wines (winery_id, name, style) values (12,'Arcturos Gewurztraminer','Gewurztraminer');
insert into wines (winery_id, name, style) values (12,'Black Star Farms Hard Apple Cherry Cider','Cider');
insert into wines (winery_id, name, style) values (12,'Red House Rose','Rose');
insert into wines (winery_id, name, style) values (12,'Arcturos Dry Riesling','Riesling');
insert into wines (winery_id, name, style) values (12,'Arcturos Sur Lie Chardonnay','Chardonnay');
insert into wines (winery_id, name, style) values (12,'Red House Rose','Rose');
insert into wines (winery_id, name, style) values (12,'Black Star Farms Pear Wine','Fruit');
insert into wines (winery_id, name, style) values (12,'Artisan Red','Sweet Red');
insert into wines (winery_id, name, style) values (12,'Sirius Red Dessert Wine','Dessert');
insert into wines (winery_id, name, style) values (12,'Spirit of the Vineyard Red Grappa','Spirit');
insert into wines (winery_id, name, style) values (12,'Spirit of Apple Brandy','Spirit');
insert into wines (winery_id, name, style) values (14,'Tropic','Sparkling');
insert into wines (winery_id, name, style) values (14,'Green','Sparkling');
insert into wines (winery_id, name, style) values (14,'Grace','Sparkling');
insert into wines (winery_id, name, style) values (14,'Sunlight','Sparkling');
insert into wines (winery_id, name, style) values (7,'Brute Rose','Sparkling');
insert into wines (winery_id, name, style) values (7,'Dry Riesling','Riesling');
insert into wines (winery_id, name, style) values (7,'Gruner Veltliner 2020','White');
insert into wines (winery_id, name, style) values (7,'Blaufrankisch 2017','Red');
insert into wines (winery_id, name, style) values (7,'Cabernet Franc 2017','Red');
insert into wines (winery_id, name, style) values (7,'Blanc De Noirs','Sparkling');
insert into wines (winery_id, name, style) values (7,'Barrel Fermented Chardonnay 2017','Chardonnay');
insert into wines (winery_id, name, style) values (7,'Pinot Grigio 2018','Pinto Grigio');
insert into wines (winery_id, name, style) values (7,'Radiance','Red');
insert into wines (winery_id, name, style) values (7,'Rosso','Red');
insert into wines (winery_id, name, style) values (7,'Blaufrankisch 2016','Red');
insert into wines (winery_id, name, style) values (7,'Blanc De Noirs','Sparkling');
insert into wines (winery_id, name, style) values (7,'Serata Demi-Sec','Sparkling');
insert into wines (winery_id, name, style) values (7,'Dry Riesling 2020','Riesling');
insert into wines (winery_id, name, style) values (7,'Medium Sweet Gewurztraminer 2020','Gewurztraminer');
insert into wines (winery_id, name, style) values (7,'Blaufrankisch','Red');
insert into wines (winery_id, name, style) values (1,'Brut Champagne','Sparkling');
insert into wines (winery_id, name, style) values (1,'Sweet Nancie','Sparkling');
insert into wines (winery_id, name, style) values (1,'BR Gruner Veltliner','White');
insert into wines (winery_id, name, style) values (1,'Outlook','Rose');
insert into wines (winery_id, name, style) values (1,'Michigan Awesome Red','Red');
insert into wines (winery_id, name, style) values (1,'Bourbon','Spirit');
insert into wines (winery_id, name, style) values (1,'Founders Pride','Dessert');
insert into wines (winery_id, name, style) values (1,'BR Blanc de Blanc','Sparkling');
insert into wines (winery_id, name, style) values (1,'Ciao Bolle','Sparkling');
insert into wines (winery_id, name, style) values (1,'Reserve Pinot Grigio','Pinot Grigio');
insert into wines (winery_id, name, style) values (1,'Cento','Sweet Red');
insert into wines (winery_id, name, style) values (1,'Cherry Hard Cider','Cider');
insert into wines (winery_id, name, style) values (1,'Original Hard Cider','Cider');
insert into wines (winery_id, name, style) values (1,'BR Albarino','White');
insert into wines (winery_id, name, style) values (1,'Mayhem','White');
insert into wines (winery_id, name, style) values (1,'Unparalleled Sweet','White');
insert into wines (winery_id, name, style) values (1,'BR Late Harvest Vignoles','White');
insert into wines (winery_id, name, style) values (1,'BR Cabernet Sauvignon','Red');
insert into wines (winery_id, name, style) values (1,'BR Chancellor','Red');
insert into wines (winery_id, name, style) values (1,'Red Heron','Sweet Red');
insert into wines (winery_id, name, style) values (1,'BR Meconi','Sweet Red');
insert into wines (winery_id, name, style) values (1,'2020 Winemakers Series Unoaked Chardonnay','Chardonnay');
insert into wines (winery_id, name, style) values (1,'2018 BR Tempranillo','Ree');
insert into wines (winery_id, name, style) values (1,'Reserve Pinot Grigio','Pinot Grigio');
insert into wines (winery_id, name, style) values (1,'Sweet Revenge','Sweet Red');
insert into wines (winery_id, name, style) values (1,'Egg Nog','Dessert');
insert into wines (winery_id, name, style) values (1,'Cranberry','Fruit');
insert into wines (winery_id, name, style) values (1,'2020 WMS White Cabernet Franc','White');
insert into wines (winery_id, name, style) values (1,'2018 Signature Series Dry Red Blend','Red');
insert into wines (winery_id, name, style) values (1,'Reserve Pinot Grigio','Pinot Grigio');
insert into wines (winery_id, name, style) values (1,'Coastline Red Blend','Red');
insert into wines (winery_id, name, style) values (1,'BR Petite Pearl','Red');
insert into wines (winery_id, name, style) values (1,'Apple Brandy','Spirit');
insert into wines (winery_id, name, style) values (1,'Vodka Made from Grapes','Spirit');
